// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA9fyVEogUb5F549HxnKzQprvTBMmFG2E',
    appId: '1:47817472751:web:00e9a59c76e6aa5b58f91a',
    messagingSenderId: '47817472751',
    projectId: 'heylo-1688c',
    authDomain: 'heylo-1688c.firebaseapp.com',
    storageBucket: 'heylo-1688c.appspot.com',
    measurementId: 'G-PMPW99THT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3LPVwC56SbHKTZnn2k7gCFv2oza4C1M',
    appId: '1:47817472751:android:755711a183f7526c58f91a',
    messagingSenderId: '47817472751',
    projectId: 'heylo-1688c',
    storageBucket: 'heylo-1688c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZK2OKIEOr7lBYJD5mcfkJ9jrwB7fYyZk',
    appId: '1:47817472751:ios:3fd1a56974e6078358f91a',
    messagingSenderId: '47817472751',
    projectId: 'heylo-1688c',
    storageBucket: 'heylo-1688c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZK2OKIEOr7lBYJD5mcfkJ9jrwB7fYyZk',
    appId: '1:47817472751:ios:62c11d6522ebd40558f91a',
    messagingSenderId: '47817472751',
    projectId: 'heylo-1688c',
    storageBucket: 'heylo-1688c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
